/* 
 * Strava API v3
 *
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * OpenAPI spec version: 3.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DetailedAthlete
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DetailedAthleteTests
    {
        // TODO uncomment below to declare an instance variable for DetailedAthlete
        //private DetailedAthlete instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DetailedAthlete
            //instance = new DetailedAthlete();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DetailedAthlete
        /// </summary>
        [Test]
        public void DetailedAthleteInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DetailedAthlete
            //Assert.IsInstanceOfType<DetailedAthlete> (instance, "variable 'instance' is a DetailedAthlete");
        }


        /// <summary>
        /// Test the property 'FollowerCount'
        /// </summary>
        [Test]
        public void FollowerCountTest()
        {
            // TODO unit test for the property 'FollowerCount'
        }
        /// <summary>
        /// Test the property 'FriendCount'
        /// </summary>
        [Test]
        public void FriendCountTest()
        {
            // TODO unit test for the property 'FriendCount'
        }
        /// <summary>
        /// Test the property 'MeasurementPreference'
        /// </summary>
        [Test]
        public void MeasurementPreferenceTest()
        {
            // TODO unit test for the property 'MeasurementPreference'
        }
        /// <summary>
        /// Test the property 'Ftp'
        /// </summary>
        [Test]
        public void FtpTest()
        {
            // TODO unit test for the property 'Ftp'
        }
        /// <summary>
        /// Test the property 'Weight'
        /// </summary>
        [Test]
        public void WeightTest()
        {
            // TODO unit test for the property 'Weight'
        }
        /// <summary>
        /// Test the property 'Clubs'
        /// </summary>
        [Test]
        public void ClubsTest()
        {
            // TODO unit test for the property 'Clubs'
        }
        /// <summary>
        /// Test the property 'Bikes'
        /// </summary>
        [Test]
        public void BikesTest()
        {
            // TODO unit test for the property 'Bikes'
        }
        /// <summary>
        /// Test the property 'Shoes'
        /// </summary>
        [Test]
        public void ShoesTest()
        {
            // TODO unit test for the property 'Shoes'
        }

    }

}
