/* 
 * Strava API v3
 *
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * OpenAPI spec version: 3.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DetailedActivity
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DetailedActivityTests
    {
        // TODO uncomment below to declare an instance variable for DetailedActivity
        //private DetailedActivity instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DetailedActivity
            //instance = new DetailedActivity();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DetailedActivity
        /// </summary>
        [Test]
        public void DetailedActivityInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DetailedActivity
            //Assert.IsInstanceOfType<DetailedActivity> (instance, "variable 'instance' is a DetailedActivity");
        }


        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Photos'
        /// </summary>
        [Test]
        public void PhotosTest()
        {
            // TODO unit test for the property 'Photos'
        }
        /// <summary>
        /// Test the property 'Gear'
        /// </summary>
        [Test]
        public void GearTest()
        {
            // TODO unit test for the property 'Gear'
        }
        /// <summary>
        /// Test the property 'Calories'
        /// </summary>
        [Test]
        public void CaloriesTest()
        {
            // TODO unit test for the property 'Calories'
        }
        /// <summary>
        /// Test the property 'SegmentEfforts'
        /// </summary>
        [Test]
        public void SegmentEffortsTest()
        {
            // TODO unit test for the property 'SegmentEfforts'
        }
        /// <summary>
        /// Test the property 'DeviceName'
        /// </summary>
        [Test]
        public void DeviceNameTest()
        {
            // TODO unit test for the property 'DeviceName'
        }
        /// <summary>
        /// Test the property 'EmbedToken'
        /// </summary>
        [Test]
        public void EmbedTokenTest()
        {
            // TODO unit test for the property 'EmbedToken'
        }
        /// <summary>
        /// Test the property 'SplitsMetric'
        /// </summary>
        [Test]
        public void SplitsMetricTest()
        {
            // TODO unit test for the property 'SplitsMetric'
        }
        /// <summary>
        /// Test the property 'SplitsStandard'
        /// </summary>
        [Test]
        public void SplitsStandardTest()
        {
            // TODO unit test for the property 'SplitsStandard'
        }
        /// <summary>
        /// Test the property 'Laps'
        /// </summary>
        [Test]
        public void LapsTest()
        {
            // TODO unit test for the property 'Laps'
        }
        /// <summary>
        /// Test the property 'BestEfforts'
        /// </summary>
        [Test]
        public void BestEffortsTest()
        {
            // TODO unit test for the property 'BestEfforts'
        }

    }

}
