/* 
 * Strava API v3
 *
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * OpenAPI spec version: 3.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SummaryClub
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SummaryClubTests
    {
        // TODO uncomment below to declare an instance variable for SummaryClub
        //private SummaryClub instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SummaryClub
            //instance = new SummaryClub();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SummaryClub
        /// </summary>
        [Test]
        public void SummaryClubInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SummaryClub
            //Assert.IsInstanceOfType<SummaryClub> (instance, "variable 'instance' is a SummaryClub");
        }


        /// <summary>
        /// Test the property 'ProfileMedium'
        /// </summary>
        [Test]
        public void ProfileMediumTest()
        {
            // TODO unit test for the property 'ProfileMedium'
        }
        /// <summary>
        /// Test the property 'CoverPhoto'
        /// </summary>
        [Test]
        public void CoverPhotoTest()
        {
            // TODO unit test for the property 'CoverPhoto'
        }
        /// <summary>
        /// Test the property 'CoverPhotoSmall'
        /// </summary>
        [Test]
        public void CoverPhotoSmallTest()
        {
            // TODO unit test for the property 'CoverPhotoSmall'
        }
        /// <summary>
        /// Test the property 'SportType'
        /// </summary>
        [Test]
        public void SportTypeTest()
        {
            // TODO unit test for the property 'SportType'
        }
        /// <summary>
        /// Test the property 'ActivityTypes'
        /// </summary>
        [Test]
        public void ActivityTypesTest()
        {
            // TODO unit test for the property 'ActivityTypes'
        }
        /// <summary>
        /// Test the property 'City'
        /// </summary>
        [Test]
        public void CityTest()
        {
            // TODO unit test for the property 'City'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Test]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Test]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }
        /// <summary>
        /// Test the property '_Private'
        /// </summary>
        [Test]
        public void _PrivateTest()
        {
            // TODO unit test for the property '_Private'
        }
        /// <summary>
        /// Test the property 'MemberCount'
        /// </summary>
        [Test]
        public void MemberCountTest()
        {
            // TODO unit test for the property 'MemberCount'
        }
        /// <summary>
        /// Test the property 'Featured'
        /// </summary>
        [Test]
        public void FeaturedTest()
        {
            // TODO unit test for the property 'Featured'
        }
        /// <summary>
        /// Test the property 'Verified'
        /// </summary>
        [Test]
        public void VerifiedTest()
        {
            // TODO unit test for the property 'Verified'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Test]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

    }

}
