/*
 * Strava API v3
 *
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * OpenAPI spec version: 3.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Attributes;
using IO.Swagger.Security;
using Microsoft.AspNetCore.Authorization;
using IO.Swagger.Models;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class SegmentEffortsApiController : ControllerBase
    { 
        /// <summary>
        /// List Segment Efforts
        /// </summary>
        /// <remarks>Returns a set of the authenticated athlete&#x27;s segment efforts for a given segment.  Requires subscription.</remarks>
        /// <param name="segmentId">The identifier of the segment.</param>
        /// <param name="startDateLocal">ISO 8601 formatted date time.</param>
        /// <param name="endDateLocal">ISO 8601 formatted date time.</param>
        /// <param name="perPage">Number of items per page. Defaults to 30.</param>
        /// <response code="200">List of segment efforts.</response>
        /// <response code="0">Unexpected error.</response>
        [HttpGet]
        [Route("/api/v3/segment_efforts")]
        [ValidateModelState]
        [SwaggerOperation("GetEffortsBySegmentId")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<DetailedSegmentEffort>), description: "List of segment efforts.")]
        [SwaggerResponse(statusCode: 0, type: typeof(Fault), description: "Unexpected error.")]
        public virtual IActionResult GetEffortsBySegmentId([FromQuery][Required()]int? segmentId, [FromQuery]DateTime? startDateLocal, [FromQuery]DateTime? endDateLocal, [FromQuery]int? perPage)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(List<DetailedSegmentEffort>));

            //TODO: Uncomment the next line to return response 0 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(0, default(Fault));
            string exampleJson = null;
            exampleJson = "[ \"\", \"\" ]";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<List<DetailedSegmentEffort>>(exampleJson)
                        : default(List<DetailedSegmentEffort>);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// Get Segment Effort
        /// </summary>
        /// <remarks>Returns a segment effort from an activity that is owned by the authenticated athlete. Requires subscription.</remarks>
        /// <param name="id">The identifier of the segment effort.</param>
        /// <response code="200">Representation of a segment effort.</response>
        /// <response code="0">Unexpected error.</response>
        [HttpGet]
        [Route("/api/v3/segment_efforts/{id}")]
        [ValidateModelState]
        [SwaggerOperation("GetSegmentEffortById")]
        [SwaggerResponse(statusCode: 200, type: typeof(DetailedSegmentEffort), description: "Representation of a segment effort.")]
        [SwaggerResponse(statusCode: 0, type: typeof(Fault), description: "Unexpected error.")]
        public virtual IActionResult GetSegmentEffortById([FromRoute][Required]long? id)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(DetailedSegmentEffort));

            //TODO: Uncomment the next line to return response 0 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(0, default(Fault));
            string exampleJson = null;
            exampleJson = "\"\"";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<DetailedSegmentEffort>(exampleJson)
                        : default(DetailedSegmentEffort);            //TODO: Change the data returned
            return new ObjectResult(example);
        }
    }
}
