// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyActiveLife.Database;

#nullable disable

namespace MyActiveLife.Database.Migrations
{
    [DbContext(typeof(MyActiveLifeDbContext))]
    [Migration("20220609164603_Entries")]
    partial class Entries
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MyActiveLife.Database.Entities.Activity", b =>
                {
                    b.Property<Guid>("ActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActivityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ActivityTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExternalId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WeatherId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ActivityId");

                    b.HasIndex("ActivityTypeId");

                    b.HasIndex("EntryId");

                    b.HasIndex("SourceId");

                    b.HasIndex("UserId");

                    b.HasIndex("WeatherId");

                    b.ToTable("Activity");
                });

            modelBuilder.Entity("MyActiveLife.Database.Entities.ActivityType", b =>
                {
                    b.Property<int>("ActivityTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActivityTypeId"), 1L, 1);

                    b.Property<string>("ActivityTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ActivityTypeId");

                    b.ToTable("ActivityType");
                });

            modelBuilder.Entity("MyActiveLife.Database.Entities.Diary", b =>
                {
                    b.Property<Guid>("DiaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Entry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DiaryId");

                    b.HasIndex("UserId");

                    b.ToTable("Diary");
                });

            modelBuilder.Entity("MyActiveLife.Database.Entities.Entry", b =>
                {
                    b.Property<Guid>("EntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("Date");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EntryId");

                    b.HasIndex("UserId");

                    b.ToTable("Entry");
                });

            modelBuilder.Entity("MyActiveLife.Database.Entities.Photo", b =>
                {
                    b.Property<Guid>("PhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PhotoId");

                    b.HasIndex("SourceId");

                    b.HasIndex("UserId");

                    b.ToTable("Photo");
                });

            modelBuilder.Entity("MyActiveLife.Database.Entities.Phq9", b =>
                {
                    b.Property<Guid>("Phq9Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Answer1")
                        .HasColumnType("int");

                    b.Property<int>("Answer2")
                        .HasColumnType("int");

                    b.Property<int>("Answer3")
                        .HasColumnType("int");

                    b.Property<int>("Answer4")
                        .HasColumnType("int");

                    b.Property<int>("Answer5")
                        .HasColumnType("int");

                    b.Property<int>("Answer6")
                        .HasColumnType("int");

                    b.Property<int>("Answer7")
                        .HasColumnType("int");

                    b.Property<int>("Answer8")
                        .HasColumnType("int");

                    b.Property<int>("Answer9")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Phq9Id");

                    b.HasIndex("UserId");

                    b.ToTable("Phq9s");
                });

            modelBuilder.Entity("MyActiveLife.Database.Entities.Source", b =>
                {
                    b.Property<Guid>("SourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SourceId");

                    b.ToTable("Source");
                });

            modelBuilder.Entity("MyActiveLife.Database.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("UserProfile");
                });

            modelBuilder.Entity("MyActiveLife.Database.Entities.Weather", b =>
                {
                    b.Property<Guid>("WeatherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<float?>("Dewpoint")
                        .HasColumnType("real");

                    b.Property<float?>("MaxTemperature")
                        .HasColumnType("real");

                    b.Property<float?>("MinTemperature")
                        .HasColumnType("real");

                    b.Property<float?>("Precipitation")
                        .HasColumnType("real");

                    b.Property<string>("StationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("Temperature")
                        .HasColumnType("real");

                    b.Property<int?>("WindDirection")
                        .HasColumnType("int");

                    b.Property<float?>("WindGust")
                        .HasColumnType("real");

                    b.Property<float?>("WindSpeed")
                        .HasColumnType("real");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WeatherId");

                    b.ToTable("Weather");
                });

            modelBuilder.Entity("MyActiveLife.Database.Entities.StravaActivity", b =>
                {
                    b.HasBaseType("MyActiveLife.Database.Entities.Activity");

                    b.Property<float?>("AverageCadence")
                        .HasColumnType("real");

                    b.Property<float?>("AverageSpeed")
                        .HasColumnType("real");

                    b.Property<float?>("AverageTemp")
                        .HasColumnType("real");

                    b.Property<float?>("AverageWatts")
                        .HasColumnType("real");

                    b.Property<float?>("Calories")
                        .HasColumnType("real");

                    b.Property<float?>("Distance")
                        .HasColumnType("real");

                    b.Property<TimeSpan>("ElapsedTime")
                        .HasColumnType("time");

                    b.Property<float?>("ElevationHigh")
                        .HasColumnType("real");

                    b.Property<float?>("ElevationLow")
                        .HasColumnType("real");

                    b.Property<float?>("Kilojoules")
                        .HasColumnType("real");

                    b.Property<string>("MapPolyline")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("MaxSpeed")
                        .HasColumnType("real");

                    b.Property<float?>("MaxWatts")
                        .HasColumnType("real");

                    b.Property<TimeSpan>("MovingTime")
                        .HasColumnType("time");

                    b.Property<float?>("SufferScore")
                        .HasColumnType("real");

                    b.Property<float?>("TotalElevationGain")
                        .HasColumnType("real");

                    b.Property<float?>("WeightedAverageWatts")
                        .HasColumnType("real");

                    b.ToTable("StravaActivity");
                });

            modelBuilder.Entity("MyActiveLife.Database.Entities.Activity", b =>
                {
                    b.HasOne("MyActiveLife.Database.Entities.ActivityType", "ActivityType")
                        .WithMany("Activities")
                        .HasForeignKey("ActivityTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyActiveLife.Database.Entities.Entry", "Entry")
                        .WithMany("Activities")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyActiveLife.Database.Entities.Source", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyActiveLife.Database.Entities.UserProfile", "UserProfile")
                        .WithMany("Activities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyActiveLife.Database.Entities.Weather", "Weather")
                        .WithMany()
                        .HasForeignKey("WeatherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ActivityType");

                    b.Navigation("Entry");

                    b.Navigation("Source");

                    b.Navigation("UserProfile");

                    b.Navigation("Weather");
                });

            modelBuilder.Entity("MyActiveLife.Database.Entities.Diary", b =>
                {
                    b.HasOne("MyActiveLife.Database.Entities.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("MyActiveLife.Database.Entities.Entry", b =>
                {
                    b.HasOne("MyActiveLife.Database.Entities.UserProfile", "Profile")
                        .WithMany("Entries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("MyActiveLife.Database.Entities.Photo", b =>
                {
                    b.HasOne("MyActiveLife.Database.Entities.Source", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyActiveLife.Database.Entities.UserProfile", "UserProfile")
                        .WithMany("Photos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Source");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("MyActiveLife.Database.Entities.Phq9", b =>
                {
                    b.HasOne("MyActiveLife.Database.Entities.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("MyActiveLife.Database.Entities.StravaActivity", b =>
                {
                    b.HasOne("MyActiveLife.Database.Entities.Activity", null)
                        .WithOne()
                        .HasForeignKey("MyActiveLife.Database.Entities.StravaActivity", "ActivityId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyActiveLife.Database.Entities.ActivityType", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("MyActiveLife.Database.Entities.Entry", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("MyActiveLife.Database.Entities.UserProfile", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Entries");

                    b.Navigation("Photos");
                });
#pragma warning restore 612, 618
        }
    }
}
