/*
 * Strava API v3
 *
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * OpenAPI spec version: 3.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class SummaryPRSegmentEffort : IEquatable<SummaryPRSegmentEffort>
    { 
        /// <summary>
        /// The unique identifier of the activity related to the PR effort.
        /// </summary>
        /// <value>The unique identifier of the activity related to the PR effort.</value>

        [DataMember(Name="pr_activity_id")]
        public long? PrActivityId { get; set; }

        /// <summary>
        /// The elapsed time ot the PR effort.
        /// </summary>
        /// <value>The elapsed time ot the PR effort.</value>

        [DataMember(Name="pr_elapsed_time")]
        public int? PrElapsedTime { get; set; }

        /// <summary>
        /// The time at which the PR effort was started.
        /// </summary>
        /// <value>The time at which the PR effort was started.</value>

        [DataMember(Name="pr_date")]
        public DateTime? PrDate { get; set; }

        /// <summary>
        /// Number of efforts by the authenticated athlete on this segment.
        /// </summary>
        /// <value>Number of efforts by the authenticated athlete on this segment.</value>

        [DataMember(Name="effort_count")]
        public int? EffortCount { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SummaryPRSegmentEffort {\n");
            sb.Append("  PrActivityId: ").Append(PrActivityId).Append("\n");
            sb.Append("  PrElapsedTime: ").Append(PrElapsedTime).Append("\n");
            sb.Append("  PrDate: ").Append(PrDate).Append("\n");
            sb.Append("  EffortCount: ").Append(EffortCount).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((SummaryPRSegmentEffort)obj);
        }

        /// <summary>
        /// Returns true if SummaryPRSegmentEffort instances are equal
        /// </summary>
        /// <param name="other">Instance of SummaryPRSegmentEffort to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SummaryPRSegmentEffort other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    PrActivityId == other.PrActivityId ||
                    PrActivityId != null &&
                    PrActivityId.Equals(other.PrActivityId)
                ) && 
                (
                    PrElapsedTime == other.PrElapsedTime ||
                    PrElapsedTime != null &&
                    PrElapsedTime.Equals(other.PrElapsedTime)
                ) && 
                (
                    PrDate == other.PrDate ||
                    PrDate != null &&
                    PrDate.Equals(other.PrDate)
                ) && 
                (
                    EffortCount == other.EffortCount ||
                    EffortCount != null &&
                    EffortCount.Equals(other.EffortCount)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (PrActivityId != null)
                    hashCode = hashCode * 59 + PrActivityId.GetHashCode();
                    if (PrElapsedTime != null)
                    hashCode = hashCode * 59 + PrElapsedTime.GetHashCode();
                    if (PrDate != null)
                    hashCode = hashCode * 59 + PrDate.GetHashCode();
                    if (EffortCount != null)
                    hashCode = hashCode * 59 + EffortCount.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(SummaryPRSegmentEffort left, SummaryPRSegmentEffort right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(SummaryPRSegmentEffort left, SummaryPRSegmentEffort right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
